name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Cinstrument-coverage
  LLVM_PROFILE_FILE=: cargo-test-%p-%m.profraw

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Generate coverage report
        run: |
          rustup component add llvm-tools-preview
          cargo install grcov
          grcov . --binary-path ./target/debug/deps/ -s . -t html --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o target/coverage/html
      - name: Deploy to GitHub Pages
        run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git checkout --orphan gh-pages
            git rm -rf .
            mkdir coverage
            cp -r target/coverage/html/* ./coverage
            git add coverage
            git commit -m "Deploy coverage report to GitHub Pages"
            git push -u origin gh-pages --force
